version: '3.8'

services:
  bot:
    build: .
    env_file:
      - telegram_bot/.env
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - .:/app
      - users_db_volume:/app/telegram_bot/utils
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

volumes:
  users_db_volume: